### 全局token
@Authorization = Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuZXdVc2VyIiwiaWF0IjoxNzM4MDM0NTI3LCJleHAiOjE3MzgwMzgxMjd9.1T4lY_86lNiZOZVtYKVn5qKdCZFIJ2yJXAmspMopqP8
@refreshToken = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJuZXdVc2VyIiwiaWF0IjoxNzM4MDIyMjg4LCJleHAiOjE3MzgxMDg2ODh9.c1KHd9AtgyGqsbD0-BaI_9IJyoc4OLNIycfOGZEPNAch6-OCiCmVZ5naGCC9fuOaEueRJOCsuCx8aMK47C4d5Q
### 获取所有聊天3.5消息
GET http://localhost:8088/1002/messages
Accept: application/json
Authorization: {{Authorization}}

### 发送聊天3.5消息
POST http://localhost:8088/1002/send
Content-Type: application/json
Authorization: {{Authorization}}

{
  "time": "2023-01-01 10:00:00",
  "msg": "Hi, this is a test message!",
  "uid": "User"
}

### 获取所有聊天4消息
GET http://localhost:8088/1003/messages
Accept: application/json
Authorization: {{Authorization}}

### 发送聊天4消息
POST http://localhost:8088/1003/send
Content-Type: application/json
Authorization: {{Authorization}}

{
  "time": "2023-01-01 10:00:00",
  "msg": "Hello from ChatGPT 4!",
  "uid": "User",
  "username": "newUser"
}

### 清除聊天消息
DELETE http://localhost:8088/chat/clear
Accept: application/json
Authorization: {{Authorization}}

### 获取好友列表
GET http://localhost:8088/friend/friendList
Accept: application/json
Authorization: {{Authorization}}

### 用户登录
POST http://localhost:8088/user/login
Content-Type: application/json

{
  "username": "newUser",
  "password": "@newPassword123"
}

### 用户注册
POST http://localhost:8088/user/register
Content-Type: application/json

{
  "username": "newUser",
  "email": "newUser12334@example.com",
  "password": "@newPassword123"
}

### 刷新令牌请求
POST http://localhost:8088/user/refresh
Content-Type: application/json

{
  "username": "newUser",
  "refreshToken": "{{refreshToken}}"
}

### 刷新令牌请求
POST http://localhost:8088/user/token
