### 全局token
@Authorization = Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuZXdVc2VyIiwiaWF0IjoxNzM3OTk1Njg1LCJleHAiOjE3Mzc5OTkyODV9.sg-oANAz-HQpkJBfWlG5aIjfCbNCv16h55MoOLCy274
@refreshToken = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJuZXdVc2VyIiwiaWF0IjoxNzM3OTk2MDAwLCJleHAiOjE3MzgwODI0MDB9.5JjGZqAlO1b1DDyT2jhvoWttDG3R7I-XMFKgOe6elZk8Lkok0B0pClRZz0pCHEthbLzWnyhUV1Q8s9_k4lqRcA
### 获取所有聊天3.5消息
GET http://localhost:8088/1002/messages
Accept: application/json
Authorization: {{Authorization}}

### 发送聊天3.5消息
POST http://localhost:8088/1002/send
Content-Type: application/json
Authorization: {{Authorization}}

{
  "time": "2023-01-01 10:00:00",
  "msg": "Hi, this is a test message!",
  "uid": "User"
}

### 获取所有聊天4消息
GET http://localhost:8088/1003/messages
Accept: application/json
Authorization: {{Authorization}}

### 发送聊天4消息
POST http://localhost:8088/1003/send
Content-Type: application/json
Authorization: {{Authorization}}

{
  "time": "2023-01-01 10:00:00",
  "msg": "Hello from ChatGPT 4!",
  "uid": "User",
  "username": "newUser"
}

### 清除聊天消息
DELETE http://localhost:8088/chat/clear
Accept: application/json
Authorization: {{Authorization}}

### 获取好友列表
GET http://localhost:8088/friend/friendList
Accept: application/json
Authorization: {{Authorization}}

### 用户登录
POST http://localhost:8088/user/login
Content-Type: application/json

{
  "username": "newUser",
  "password": "@newPassword123"
}

### 用户注册
POST http://localhost:8088/user/register
Content-Type: application/json

{
  "username": "newUser",
  "email": "newUser12334@example.com",
  "password": "@newPassword123"
}

### 刷新令牌请求
POST http://localhost:8088/user/refresh
Content-Type: application/json

{
  "username": "newUser",
  "refreshToken": "{{refreshToken}}"
}
