### 全局token
@Authorization = Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuZXdVc2VyIiwiaWF0IjoxNzM5MTA0MzM5LCJleHAiOjE3MzkxMDc5Mzl9.tbBFum2DPetMgI6X9pWCX9_1T8VtwT6IcaeO4JSrkVY
@refreshToken = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJuZXdVc2VyIiwiaWF0IjoxNzM4NDc1OTQ2LCJleHAiOjE3Mzg1NjIzNDZ9.-ePx4i5lLYbVOsQKsYsQJedDklku1udNuJw1XSxcvxIa7nN_W44IQ6E3yQUaAx3o-2IFwepVJ3uHhILHZ8iAoA

### 获取所有聊天3.5消息
POST http://localhost:8088/1002/messages
Accept: application/json
Authorization: {{Authorization}}
### 发送聊天3.5消息
POST http://localhost:8088/1002/send
Content-Type: application/json
Authorization: {{Authorization}}

{
  "time": "2023-01-01 10:00:00",
  "content": "写一份kt代码",
  "role": "User"
}

### 获取所有聊天4消息
POST http://localhost:8088/1003/messages
Accept: application/json
Authorization: {{Authorization}}

### 发送聊天4消息
POST http://localhost:8088/1003/send
Content-Type: application/json
Authorization: {{Authorization}}

{
  "time": "2023-01-01 10:00:00",
  "content": "Hello from ChatGPT 4!",
  "role": "User",
  "username": "newUser"
}
### 获取所有聊天3.5消息
POST http://localhost:8088/1004/messages
Accept: application/json
Content-Type: application/json
Authorization: {{Authorization}}

{}
### 发送DeepSeek消息
POST http://localhost:8088/1004/send
Content-Type: application/json
Authorization: {{Authorization}}

{
  "time": "2023-01-01 10:00:00",
  "content": "不对!",
  "role": "User",
  "username": "newUser"
}
### 清除聊天消息
DELETE http://localhost:8088/chat/clear
Accept: application/json
Authorization: {{Authorization}}

### 聊天记录恢复
POST http://localhost:8088/chat/revert
Accept: application/json
Authorization: {{Authorization}}

### 获取好友列表
POST http://localhost:8088/friend/friendList
Accept: application/json
Authorization: {{Authorization}}

### 用户登录(newUser)
POST https://a007-113-224-213-152.ngrok-free.app/user/login
Content-Type: application/json

{
  "username": "newUser",
  "password": "@newPassword123"
}

### 用户登录(hhyufan)
POST https://a007-113-224-213-152.ngrok-free.app/user/login
Content-Type: application/json

{
  "username": "hhyufan",
  "password": "@Mimo521"
}

### 用户登出
POST http://localhost:8088/user/logout
Accept: application/json
Authorization: {{Authorization}}

### 用户注册
POST http://localhost:8088/user/register
Content-Type: application/json

{
  "username": "newU[1sr",
  "email": "newUer13341@example.com",
  "password": "@newPassword123"
}

### 刷新令牌请求
POST http://localhost:8088/user/refresh
Content-Type: application/json
Authorization: {{Authorization}}

{
  "username": "newUser",
  "refreshToken": "{{refreshToken}}"
}

### 获取新的token
POST http://localhost:8088/user/token
Authorization: {{Authorization}}

### 获取GitHub收藏数
POST http://localhost:8088/github/stars

#### Groq API Chat Completion Request
POST https://api.deepseek.com/chat/completions
Content-Type: application/json
Authorization: Bearer

{
  "model": "deepseek-chat",
  "messages": [
    {
      "role": "system",
      "content": "你是一个经验丰富的全栈开发者，帮助我解决关于网页开发的问题。"
    },
    {
      "role": "user",
      "content": "在大型应用中，如何有效地管理组件状态，特别是在使用React、Vue或Angular等框架时？。"
    }
  ]
}
